package main

import (
	"context"
	"net/url"
	"strings"
	"sync"
	"time"
)

const (
	// Browser image generation can legitimately continue after a provider's
	// ordinary text-response detector has decided the turn is done. Keep the
	// bridge alive long enough to collect the actual generated asset instead of
	// texting an intermediate "Image"/"Creating your image" placeholder.
	browserChatGeneratedImageWait = 4 * time.Minute
	browserChatInitialMediaWait   = 3 * time.Second
)

// browserChatReturnedMedia is the media that belongs to the browser-chat turn
// that just finished. Browser turns are serialized by Bridge, so one guarded
// slot is enough and prevents an asset from leaking into the next SMS.
type browserChatReturnedMedia struct {
	Kind            string
	Filename        string
	MediaType       string
	Data            []byte
	ConversationURL string
}

var (
	capturedBrowserChatMediaMu sync.Mutex
	capturedBrowserChatMedia   *browserChatReturnedMedia
)

func clearCapturedBrowserChatReturnedMedia() {
	capturedBrowserChatMediaMu.Lock()
	capturedBrowserChatMedia = nil
	capturedBrowserChatMediaMu.Unlock()
}

func storeCapturedBrowserChatReturnedMedia(m *browserChatReturnedMedia) {
	if m == nil {
		return
	}
	copyMedia := &browserChatReturnedMedia{
		Kind:            strings.ToLower(strings.TrimSpace(m.Kind)),
		Filename:        strings.TrimSpace(m.Filename),
		MediaType:       strings.ToLower(strings.TrimSpace(m.MediaType)),
		ConversationURL: safeBrowserConversationURL(m.ConversationURL),
		Data:            append([]byte(nil), m.Data...),
	}
	if copyMedia.Kind == "" {
		return
	}
	capturedBrowserChatMediaMu.Lock()
	capturedBrowserChatMedia = copyMedia
	capturedBrowserChatMediaMu.Unlock()
}

func hasCapturedBrowserChatReturnedMedia() bool {
	capturedBrowserChatMediaMu.Lock()
	defer capturedBrowserChatMediaMu.Unlock()
	return capturedBrowserChatMedia != nil
}

// waitForCapturedBrowserChatReturnedMedia waits without consuming the slot.
// Delivery owns the consume operation so the generated bytes remain available
// to GoogleVoiceSMSClient.SendReply after the browser turn has recovered.
func waitForCapturedBrowserChatReturnedMedia(ctx context.Context, timeout time.Duration) bool {
	if hasCapturedBrowserChatReturnedMedia() {
		return true
	}
	if timeout <= 0 {
		return false
	}
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	ticker := time.NewTicker(200 * time.Millisecond)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			return false
		case <-timer.C:
			return hasCapturedBrowserChatReturnedMedia()
		case <-ticker.C:
			if hasCapturedBrowserChatReturnedMedia() {
				return true
			}
		}
	}
}

func takeCapturedBrowserChatReturnedMedia() *browserChatReturnedMedia {
	capturedBrowserChatMediaMu.Lock()
	defer capturedBrowserChatMediaMu.Unlock()
	m := capturedBrowserChatMedia
	capturedBrowserChatMedia = nil
	if m == nil {
		return nil
	}
	return &browserChatReturnedMedia{
		Kind:            m.Kind,
		Filename:        m.Filename,
		MediaType:       m.MediaType,
		ConversationURL: m.ConversationURL,
		Data:            append([]byte(nil), m.Data...),
	}
}

// browserChatPromptRequestsGeneratedImage intentionally recognizes explicit
// creation requests only. It is used both on the original SMS prompt and on the
// browser-turn expression, so broad words such as "image" by themselves would
// create false positives in page-driver JavaScript.
func browserChatPromptRequestsGeneratedImage(prompt string) bool {
	s := strings.ToLower(strings.Join(strings.Fields(prompt), " "))
	if s == "" {
		return false
	}
	patterns := []string{
		"generate an image", "generate a image", "generate image", "generate me an image", "generate me a image",
		"generate a picture", "generate picture", "generate me a picture",
		"generate a photo", "generate photo", "generate me a photo",
		"create an image", "create a image", "create image", "create me an image", "create me a image",
		"create a picture", "create picture", "create me a picture",
		"create a photo", "create photo", "create me a photo",
		"make an image", "make a image", "make image", "make me an image", "make me a image",
		"make a picture", "make picture", "make me a picture",
		"make a photo", "make photo", "make me a photo",
		"draw an image", "draw a picture", "draw me a picture", "draw me an image",
		"render an image", "render a picture", "render me an image", "render me a picture",
	}
	for _, pattern := range patterns {
		if strings.Contains(s, pattern) {
			return true
		}
	}
	return false
}

// A few browser products expose a short placeholder as the assistant text
// while their image tool is still rendering. Those strings are not a completed
// answer and must not be forwarded before the media collector has had time to
// see the final image.
func browserChatReplySuggestsPendingImage(reply string) bool {
	s := strings.ToLower(strings.TrimSpace(reply))
	if s == "" {
		return true
	}
	if len([]rune(s)) > 220 {
		return false
	}
	for _, refusal := range []string{"can't generate", "cannot generate", "unable to generate", "can't create", "cannot create", "unable to create", "sorry, i can't", "sorry, i cannot"} {
		if strings.Contains(s, refusal) {
			return false
		}
	}
	switch strings.Trim(s, " .!…") {
	case "image", "picture", "photo", "creating image", "creating your image", "generating image", "generating your image":
		return true
	}
	for _, signal := range []string{
		"creating your image", "creating the image", "creating an image",
		"generating your image", "generating the image", "generating an image",
		"working on the image", "working on your image", "image is being created", "image is being generated",
	} {
		if strings.Contains(s, signal) {
			return true
		}
	}
	return false
}

// Only the five browser providers FlipAi itself controls are valid fallback
// destinations. This keeps a page element from turning into an arbitrary URL in
// an outgoing SMS.
func safeBrowserConversationURL(raw string) string {
	raw = strings.TrimSpace(raw)
	u, err := url.Parse(raw)
	if err != nil || !strings.EqualFold(u.Scheme, "https") || u.User != nil {
		return ""
	}
	host := strings.ToLower(strings.TrimSpace(u.Hostname()))
	switch host {
	case "chatgpt.com", "claude.ai", "gemini.google.com", "grok.com", "copilot.microsoft.com":
		return u.String()
	default:
		return ""
	}
}

func appendBrowserMediaConversationLink(body, conversationURL string) string {
	body = strings.TrimSpace(body)
	conversationURL = safeBrowserConversationURL(conversationURL)
	if conversationURL == "" || strings.Contains(body, conversationURL) {
		return body
	}
	if body == "" {
		return "Open the media in the chat: " + conversationURL
	}
	return body + "\n\nOpen the media in the chat: " + conversationURL
}

// prepareBrowserChatReturnedMediaReply prefers a real Google Voice image MMS.
// Google Voice's web UI accepts images but not arbitrary model files, so video,
// audio, files, or an image that cannot be normalized safely fall back to the
// provider conversation URL as requested by the user.
func prepareBrowserChatReturnedMediaReply(body string, media *browserChatReturnedMedia) (string, *outboundVoiceImage) {
	if media == nil {
		return body, nil
	}
	if strings.EqualFold(media.Kind, "image") && len(media.Data) > 0 {
		name := strings.TrimSpace(media.Filename)
		if name == "" {
			name = "flipai-generated.png"
		}
		if image, err := normalizeVoiceImage(name, media.Data); err == nil {
			return body, image
		}
	}
	return appendBrowserMediaConversationLink(body, media.ConversationURL), nil
}
