package main

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
)

// captureCodexImageFromItemCompletedFlexible handles the same live event as the
// original strict v2 parser, but tolerates older/version-skewed item spelling
// and data-URL results. Keep the strict parser as the first path; this is a
// compatibility net for the exact failure seen on a real PC.
func captureCodexImageFromItemCompletedFlexible(params json.RawMessage) bool {
	var p struct {
		Item json.RawMessage `json:"item"`
	}
	if json.Unmarshal(params, &p) != nil || len(p.Item) == 0 {
		return false
	}
	img := codexImageFromThreadItem(p.Item)
	if img == nil {
		return false
	}
	storeCapturedCodexImage(img)
	return true
}

// captureCodexImageFromTurnCompleted is an exact-turn fallback for Codex builds
// where the standalone item/completed image-generation notification is missing,
// delayed, or shaped differently. App Server's turn/completed notification
// carries the completed Turn, including its ThreadItem list, so FlipAi can take
// the already-generated bytes from the same live Codex connection without a
// second app-server process, another prompt, another image generation, or any
// model-token round trip.
func captureCodexImageFromTurnCompleted(params json.RawMessage) bool {
	var p struct {
		Turn struct {
			Items []json.RawMessage `json:"items"`
		} `json:"turn"`
	}
	if json.Unmarshal(params, &p) != nil || len(p.Turn.Items) == 0 {
		return false
	}

	// If a turn generated more than one picture, the newest completed image is
	// the one associated with the final answer the user is receiving.
	for i := len(p.Turn.Items) - 1; i >= 0; i-- {
		if img := codexImageFromThreadItem(p.Turn.Items[i]); img != nil {
			storeCapturedCodexImage(img)
			return true
		}
	}
	return false
}

func codexImageFromThreadItem(raw json.RawMessage) *outboundVoiceImage {
	var item struct {
		Type            string `json:"type"`
		Result          string `json:"result"`
		SavedPath       string `json:"savedPath"`
		LegacySavedPath string `json:"saved_path"`
	}
	if json.Unmarshal(raw, &item) != nil || !isCodexImageGenerationType(item.Type) {
		return nil
	}

	savedPath := strings.TrimSpace(item.SavedPath)
	if savedPath == "" {
		savedPath = strings.TrimSpace(item.LegacySavedPath)
	}

	if encoded := strings.TrimSpace(item.Result); encoded != "" {
		// Current Codex uses raw base64. Accept data URLs as well because older or
		// version-skewed clients may preserve the image in that equivalent form.
		if comma := strings.IndexByte(encoded, ','); comma >= 0 && strings.HasPrefix(strings.ToLower(encoded), "data:image/") {
			encoded = encoded[comma+1:]
		}
		if data, err := base64.StdEncoding.DecodeString(strings.TrimSpace(encoded)); err == nil && len(data) > 0 {
			name := "flipai-generated.png"
			if savedPath != "" {
				name = filepath.Base(savedPath)
			}
			if img, err := normalizeVoiceImage(name, data); err == nil {
				return img
			}
		}
	}

	if savedPath != "" {
		if data, err := os.ReadFile(savedPath); err == nil && len(data) > 0 {
			if img, err := normalizeVoiceImage(filepath.Base(savedPath), data); err == nil {
				return img
			}
		}
	}
	return nil
}

func isCodexImageGenerationType(kind string) bool {
	kind = strings.ToLower(strings.TrimSpace(kind))
	kind = strings.ReplaceAll(kind, "_", "")
	kind = strings.ReplaceAll(kind, "-", "")
	return kind == "imagegeneration"
}

func storeCapturedCodexImage(img *outboundVoiceImage) {
	if img == nil || len(img.Data) == 0 {
		return
	}
	copyImage := &outboundVoiceImage{
		Filename:  img.Filename,
		MediaType: img.MediaType,
		Data:      append([]byte(nil), img.Data...),
	}
	capturedCodexImageMu.Lock()
	capturedCodexImage = copyImage
	capturedCodexImageMu.Unlock()
}
